baseURL = "http://localhost:1313/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Kwaw.xyz"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = false                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 6                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                     # 必需
  name = "Yosi Kwaw"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "posts"
  url = "/posts/"
[[menu.main]]
  name = "Poems"
  weight = 20
  identifier = "poems"
  url = "/poems/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "Sometimes I Write Things"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "Hello Friend"                                   # site's footer slogan  # 网站页脚标语
  keywords = ["Personal site","poetry","essays"]                                  # site's keywords  # 网站关键字
  description = "Personal site of Yosi Kwaw"                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts", "poems"]
  customCSS = ["custom.css"]
  
[permalinks]
  posts = "/:section/:slug/"

 
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true


